-- backend/database/migrations/011_create_labels.sql
CREATE TABLE IF NOT EXISTS labels (
  key    TEXT NOT NULL,
  locale TEXT NOT NULL,
  value  TEXT NOT NULL,
  PRIMARY KEY (key, locale)
);
CREATE INDEX IF NOT EXISTS idx_labels_locale ON labels(locale);

-- locale names (used by GET /api/v1/labels/locales)
INSERT INTO labels (key, locale, value) VALUES
  ('locale.en.name', 'en', 'English'),
  ('locale.en.name', 'fr', 'Anglais'),
  ('locale.fr.name', 'en', 'French'),
  ('locale.fr.name', 'fr', 'Français'),

  -- common
  ('common.buttons.save',    'en', 'Save'),
  ('common.buttons.save',    'fr', 'Enregistrer'),
  ('common.buttons.cancel',  'en', 'Cancel'),
  ('common.buttons.cancel',  'fr', 'Annuler'),
  ('common.buttons.delete',  'en', 'Delete'),
  ('common.buttons.delete',  'fr', 'Supprimer'),
  ('common.buttons.edit',    'en', 'Edit'),
  ('common.buttons.edit',    'fr', 'Modifier'),
  ('common.buttons.add',     'en', 'Add'),
  ('common.buttons.add',     'fr', 'Ajouter'),
  ('common.buttons.confirm', 'en', 'Confirm'),
  ('common.buttons.confirm', 'fr', 'Confirmer'),
  ('common.buttons.back',    'en', 'Back'),
  ('common.buttons.back',    'fr', 'Retour'),
  ('common.buttons.retry',   'en', 'Retry'),
  ('common.buttons.retry',   'fr', 'Réessayer'),
  ('common.buttons.submit',  'en', 'Submit'),
  ('common.buttons.submit',  'fr', 'Valider'),
  ('common.buttons.create',  'en', 'Create'),
  ('common.buttons.create',  'fr', 'Créer'),
  ('common.buttons.close',   'en', 'Close'),
  ('common.buttons.close',   'fr', 'Fermer'),
  ('common.buttons.loading', 'en', 'Loading...'),
  ('common.buttons.loading', 'fr', 'Chargement...'),
  ('common.search.placeholder', 'en', 'Search...'),
  ('common.search.placeholder', 'fr', 'Rechercher...'),
  ('common.empty.no_results',   'en', 'No results found'),
  ('common.empty.no_results',   'fr', 'Aucun résultat'),
  ('common.action.cannot_undo', 'en', 'This action cannot be undone.'),
  ('common.action.cannot_undo', 'fr', 'Cette action est irréversible.'),

  -- auth
  ('auth.title',                'en', 'Board Game Dashboard'),
  ('auth.title',                'fr', 'Board Game Dashboard'),
  ('auth.subtitle',             'en', 'Enter your password to continue'),
  ('auth.subtitle',             'fr', 'Entrez votre mot de passe pour continuer'),
  ('auth.password.label',       'en', 'Password'),
  ('auth.password.label',       'fr', 'Mot de passe'),
  ('auth.submit',               'en', 'Sign in'),
  ('auth.submit',               'fr', 'Se connecter'),
  ('auth.submit.loading',       'en', 'Signing in...'),
  ('auth.submit.loading',       'fr', 'Connexion...'),
  ('auth.error.wrong_password', 'en', 'Incorrect password. Please try again.'),
  ('auth.error.wrong_password', 'fr', 'Mot de passe incorrect. Veuillez réessayer.'),

  -- dashboard
  ('dashboard.title',                   'en', 'Dashboard'),
  ('dashboard.title',                   'fr', 'Dashboard'),
  ('dashboard.tooltip.back',            'en', 'Go Back'),
  ('dashboard.tooltip.back',            'fr', 'Retour'),
  ('dashboard.tooltip.settings',        'en', 'Settings'),
  ('dashboard.tooltip.settings',        'fr', 'Paramètres'),
  ('dashboard.section.players',         'en', 'Player Statistics'),
  ('dashboard.section.players',         'fr', 'Statistiques joueurs'),
  ('dashboard.section.games',           'en', 'Recent Games'),
  ('dashboard.section.games',           'fr', 'Jeux récents'),
  ('dashboard.section.activity',        'en', 'Recent Activity'),
  ('dashboard.section.activity',        'fr', 'Activité récente'),
  ('dashboard.players.empty',           'en', 'No players yet'),
  ('dashboard.players.empty',           'fr', 'Aucun joueur'),
  ('dashboard.players.add_first',       'en', 'Add your first player'),
  ('dashboard.players.add_first',       'fr', 'Ajouter votre premier joueur'),
  ('dashboard.games.empty',             'en', 'No games yet'),
  ('dashboard.games.empty',             'fr', 'Aucun jeu'),
  ('dashboard.games.add_first',         'en', 'Add your first game'),
  ('dashboard.games.add_first',         'fr', 'Ajouter votre premier jeu'),
  ('dashboard.activity.game_started',   'en', 'New game started'),
  ('dashboard.activity.game_started',   'fr', 'Nouvelle partie démarrée'),
  ('dashboard.activity.player_joined',  'en', 'Player joined'),
  ('dashboard.activity.player_joined',  'fr', 'Joueur rejoint'),
  ('dashboard.actions.new_game',        'en', 'New Game'),
  ('dashboard.actions.new_game',        'fr', 'Nouvelle partie'),
  ('dashboard.actions.new_game.tooltip','en', 'Start a New Game Session'),
  ('dashboard.actions.new_game.tooltip','fr', 'Démarrer une nouvelle partie'),
  ('dashboard.actions.add_player',        'en', 'Add Player'),
  ('dashboard.actions.add_player',        'fr', 'Ajouter joueur'),
  ('dashboard.actions.add_player.tooltip','en', 'Go to Players Page'),
  ('dashboard.actions.add_player.tooltip','fr', 'Aller à la page joueurs'),
  ('dashboard.tooltip.view_players',    'en', 'View All Players'),
  ('dashboard.tooltip.view_players',    'fr', 'Voir tous les joueurs'),
  ('dashboard.tooltip.view_games',      'en', 'View All Games'),
  ('dashboard.tooltip.view_games',      'fr', 'Voir tous les jeux'),

  -- games page
  ('games.page.title',              'en', 'Games'),
  ('games.page.title',              'fr', 'Jeux'),
  ('games.stats.total',             'en', 'Total Games'),
  ('games.stats.total',             'fr', 'Total jeux'),
  ('games.stats.categories',        'en', 'Categories'),
  ('games.stats.categories',        'fr', 'Catégories'),
  ('games.stats.avg_rating',        'en', 'Avg Rating'),
  ('games.stats.avg_rating',        'fr', 'Note moyenne'),
  ('games.search.placeholder',      'en', 'Search games, designers, publishers...'),
  ('games.search.placeholder',      'fr', 'Rechercher jeux, créateurs, éditeurs...'),
  ('games.card.players',            'en', 'players'),
  ('games.card.players',            'fr', 'joueurs'),
  ('games.card.weight',             'en', 'Weight:'),
  ('games.card.weight',             'fr', 'Poids :'),
  ('games.card.expansion',          'en', 'Extension'),
  ('games.card.expansion',          'fr', 'Extension'),
  ('games.card.expansion.count',    'en', 'expansion'),
  ('games.card.expansion.count',    'fr', 'extension'),
  ('games.card.expansion.count_plural', 'en', 'expansions'),
  ('games.card.expansion.count_plural', 'fr', 'extensions'),
  ('games.card.character.count',        'en', 'character'),
  ('games.card.character.count',        'fr', 'personnage'),
  ('games.card.character.count_plural', 'en', 'characters'),
  ('games.card.character.count_plural', 'fr', 'personnages'),
  ('games.card.section.expansions',     'en', 'Expansions'),
  ('games.card.section.expansions',     'fr', 'Extensions'),
  ('games.card.section.characters',     'en', 'Characters/Roles'),
  ('games.card.section.characters',     'fr', 'Personnages/Rôles'),
  ('games.card.modes.competitive',  'en', 'Competitive'),
  ('games.card.modes.competitive',  'fr', 'Compétitif'),
  ('games.card.modes.cooperative',  'en', 'Cooperative'),
  ('games.card.modes.cooperative',  'fr', 'Coopératif'),
  ('games.card.modes.campaign',     'en', 'Campaign'),
  ('games.card.modes.campaign',     'fr', 'Campagne'),
  ('games.card.modes.hybrid',       'en', 'Hybrid'),
  ('games.card.modes.hybrid',       'fr', 'Hybride'),
  ('games.empty',                   'en', 'No games found'),
  ('games.empty',                   'fr', 'Aucun jeu trouvé'),
  ('games.tooltip.view_details',    'en', 'View Details'),
  ('games.tooltip.view_details',    'fr', 'Voir les détails'),
  ('games.tooltip.view_stats',      'en', 'View Game Stats'),
  ('games.tooltip.view_stats',      'fr', 'Voir les stats'),
  ('games.tooltip.edit',            'en', 'Edit Game'),
  ('games.tooltip.edit',            'fr', 'Modifier le jeu'),
  ('games.menu.view_details',       'en', 'View Details'),
  ('games.menu.view_details',       'fr', 'Voir les détails'),
  ('games.menu.view_stats',         'en', 'View Stats'),
  ('games.menu.view_stats',         'fr', 'Voir les stats'),
  ('games.menu.edit',               'en', 'Edit Game'),
  ('games.menu.edit',               'fr', 'Modifier le jeu'),
  ('games.menu.expansions',         'en', 'Manage Expansions'),
  ('games.menu.expansions',         'fr', 'Gérer les extensions'),
  ('games.menu.characters',         'en', 'Manage Characters'),
  ('games.menu.characters',         'fr', 'Gérer les personnages'),
  ('games.menu.delete',             'en', 'Delete Game'),
  ('games.menu.delete',             'fr', 'Supprimer le jeu'),
  ('games.add_dialog.title',        'en', 'Add New Game'),
  ('games.add_dialog.title',        'fr', 'Ajouter un nouveau jeu'),
  ('games.add_dialog.submit',       'en', 'Add Game'),
  ('games.add_dialog.submit',       'fr', 'Ajouter le jeu'),
  ('games.edit_dialog.title',       'en', 'Edit Game'),
  ('games.edit_dialog.title',       'fr', 'Modifier le jeu'),
  ('games.edit_dialog.submit',      'en', 'Update Game'),
  ('games.edit_dialog.submit',      'fr', 'Mettre à jour'),
  ('games.delete_dialog.title',     'en', 'Delete Game'),
  ('games.delete_dialog.title',     'fr', 'Supprimer le jeu'),
  ('games.delete_dialog.description','en','Are you sure you want to delete this game? This action cannot be undone and will also remove all associated expansions and characters.'),
  ('games.delete_dialog.description','fr','Supprimer ce jeu ? Cette action est irréversible et supprimera également toutes les extensions et personnages associés.'),
  ('games.form.name.label',              'en', 'Game Name'),
  ('games.form.name.label',              'fr', 'Nom du jeu'),
  ('games.form.name.placeholder',        'en', 'Enter game name'),
  ('games.form.name.placeholder',        'fr', 'Entrer le nom du jeu'),
  ('games.form.designer.label',          'en', 'Designer'),
  ('games.form.designer.label',          'fr', 'Créateur'),
  ('games.form.publisher.label',         'en', 'Publisher'),
  ('games.form.publisher.label',         'fr', 'Éditeur'),
  ('games.form.year.label',              'en', 'Year'),
  ('games.form.year.label',              'fr', 'Année'),
  ('games.form.bgg_rating.label',        'en', 'BGG Rating'),
  ('games.form.bgg_rating.label',        'fr', 'Note BGG'),
  ('games.form.description.label',       'en', 'Description'),
  ('games.form.description.label',       'fr', 'Description'),
  ('games.form.description.placeholder', 'en', 'Brief game description'),
  ('games.form.description.placeholder', 'fr', 'Brève description du jeu'),
  ('games.form.category.label',          'en', 'Category'),
  ('games.form.category.label',          'fr', 'Catégorie'),
  ('games.form.modes.label',             'en', 'Game Modes'),
  ('games.form.modes.label',             'fr', 'Modes de jeu'),
  ('games.form.is_expansion.label',      'en', 'Is an expansion'),
  ('games.form.is_expansion.label',      'fr', 'Est une extension'),
  ('games.form.has_expansion.label',     'en', 'Has expansions'),
  ('games.form.has_expansion.label',     'fr', 'A des extensions'),
  ('games.form.expansions.label',        'en', 'Expansions'),
  ('games.form.expansions.label',        'fr', 'Extensions'),
  ('games.form.has_characters.label',    'en', 'Has character roles'),
  ('games.form.has_characters.label',    'fr', 'A des rôles de personnages'),
  ('games.form.characters.section',      'en', 'Characters'),
  ('games.form.characters.section',      'fr', 'Personnages'),
  ('games.form.characters.name.placeholder','en', 'Character name'),
  ('games.form.characters.name.placeholder','fr', 'Nom du personnage'),
  ('games.form.characters.abilities.label','en', 'Abilities'),
  ('games.form.characters.abilities.label','fr', 'Capacités'),
  ('games.form.characters.ability.placeholder','en', 'Ability name'),
  ('games.form.characters.ability.placeholder','fr', 'Nom de la capacité'),

  -- games form validation
  ('games.form.validation.name_required',  'en', 'Game name is required'),
  ('games.form.validation.name_required',  'fr', 'Le nom du jeu est requis'),
  ('games.form.validation.name_min',       'en', 'Game name must be at least 2 characters'),
  ('games.form.validation.name_min',       'fr', 'Le nom doit contenir au moins 2 caractères'),
  ('games.form.validation.image_url',      'en', 'Please enter a valid image URL (https://...)'),
  ('games.form.validation.image_url',      'fr', 'Veuillez entrer une URL d''image valide (https://...)'),
  ('games.form.validation.min_players',    'en', 'Minimum players must be at least 1'),
  ('games.form.validation.min_players',    'fr', 'Le nombre minimum de joueurs doit être au moins 1'),
  ('games.form.validation.max_players_min','en', 'Maximum players must be at least 1'),
  ('games.form.validation.max_players_min','fr', 'Le nombre maximum de joueurs doit être au moins 1'),
  ('games.form.validation.max_players_range','en','Maximum players cannot be less than minimum'),
  ('games.form.validation.max_players_range','fr','Le maximum ne peut pas être inférieur au minimum'),
  ('games.form.validation.age',            'en', 'Age must be between 1 and 99'),
  ('games.form.validation.age',            'fr', 'L''âge doit être entre 1 et 99'),
  ('games.form.validation.bgg_rating',     'en', 'BGG Rating must be between 0 and 10'),
  ('games.form.validation.bgg_rating',     'fr', 'La note BGG doit être entre 0 et 10'),
  ('games.form.validation.weight',         'en', 'Weight must be between 0 and 5'),
  ('games.form.validation.weight',         'fr', 'La complexité doit être entre 0 et 5'),

  -- players page
  ('players.page.title',            'en', 'Players'),
  ('players.page.title',            'fr', 'Joueurs'),
  ('players.stats.total',           'en', 'Players'),
  ('players.stats.total',           'fr', 'Joueurs'),
  ('players.stats.games',           'en', 'Games'),
  ('players.stats.games',           'fr', 'Parties'),
  ('players.stats.wins',            'en', 'Wins'),
  ('players.stats.wins',            'fr', 'Victoires'),
  ('players.search.placeholder',    'en', 'Search players...'),
  ('players.search.placeholder',    'fr', 'Rechercher des joueurs...'),
  ('players.card.games',            'en', 'games'),
  ('players.card.games',            'fr', 'parties'),
  ('players.card.wins',             'en', 'wins'),
  ('players.card.wins',             'fr', 'victoires'),
  ('players.card.avg',              'en', 'Avg:'),
  ('players.card.avg',              'fr', 'Moy :'),
  ('players.card.menu.view_stats',  'en', 'View Stats'),
  ('players.card.menu.view_stats',  'fr', 'Voir les stats'),
  ('players.card.menu.edit',        'en', 'Edit'),
  ('players.card.menu.edit',        'fr', 'Modifier'),
  ('players.card.menu.delete',      'en', 'Delete'),
  ('players.card.menu.delete',      'fr', 'Supprimer'),
  ('players.empty',                 'en', 'No players found'),
  ('players.empty',                 'fr', 'Aucun joueur trouvé'),
  ('players.empty.add_first',       'en', 'Add Your First Player'),
  ('players.empty.add_first',       'fr', 'Ajouter votre premier joueur'),
  ('players.add_dialog.title',      'en', 'Add New Player'),
  ('players.add_dialog.title',      'fr', 'Ajouter un joueur'),
  ('players.edit_dialog.title',     'en', 'Edit Player'),
  ('players.edit_dialog.title',     'fr', 'Modifier le joueur'),
  ('players.delete_dialog.title',   'en', 'Delete Player'),
  ('players.delete_dialog.title',   'fr', 'Supprimer le joueur'),
  ('players.delete_dialog.description','en','Are you sure you want to delete this player? This action cannot be undone.'),
  ('players.delete_dialog.description','fr','Supprimer ce joueur ? Cette action est irréversible.'),
  ('players.form.name.label',            'en', 'Name'),
  ('players.form.name.label',            'fr', 'Nom'),
  ('players.form.avatar.label',          'en', 'Avatar URL'),
  ('players.form.avatar.label',          'fr', 'URL de l''avatar'),
  ('players.form.favorite_game.label',   'en', 'Favorite Game'),
  ('players.form.favorite_game.label',   'fr', 'Jeu favori'),
  ('players.form.favorite_game.placeholder','en', 'Enter favorite game (optional)'),
  ('players.form.favorite_game.placeholder','fr', 'Jeu favori (optionnel)'),

  -- players form validation
  ('players.form.validation.name_required','en', 'Player name is required'),
  ('players.form.validation.name_required','fr', 'Le nom du joueur est requis'),
  ('players.form.validation.name_min',     'en', 'Name must be at least 2 characters'),
  ('players.form.validation.name_min',     'fr', 'Le nom doit contenir au moins 2 caractères'),
  ('players.form.validation.name_max',     'en', 'Name cannot exceed 50 characters'),
  ('players.form.validation.name_max',     'fr', 'Le nom ne peut pas dépasser 50 caractères'),
  ('players.form.validation.pseudo_min',   'en', 'Pseudo must be at least 2 characters'),
  ('players.form.validation.pseudo_min',   'fr', 'Le pseudo doit contenir au moins 2 caractères'),
  ('players.form.validation.pseudo_max',   'en', 'Pseudo cannot exceed 50 characters'),
  ('players.form.validation.pseudo_max',   'fr', 'Le pseudo ne peut pas dépasser 50 caractères'),
  ('players.form.validation.avatar_url',   'en', 'Invalid image URL'),
  ('players.form.validation.avatar_url',   'fr', 'URL d''image invalide'),

  -- sessions
  ('sessions.new.title',                     'en', 'New Game Session'),
  ('sessions.new.title',                     'fr', 'Nouvelle partie'),
  ('sessions.setup.title',                   'en', 'Game Setup'),
  ('sessions.setup.title',                   'fr', 'Configuration'),
  ('sessions.setup.game.label',              'en', 'Game'),
  ('sessions.setup.game.label',              'fr', 'Jeu'),
  ('sessions.setup.game.placeholder',        'en', 'Choose a game...'),
  ('sessions.setup.game.placeholder',        'fr', 'Choisir un jeu...'),
  ('sessions.setup.type.label',              'en', 'Session Type'),
  ('sessions.setup.type.label',              'fr', 'Type de session'),
  ('sessions.setup.type.competitive',        'en', 'Competitive - Players compete against each other'),
  ('sessions.setup.type.competitive',        'fr', 'Compétitif - Les joueurs s''affrontent'),
  ('sessions.setup.type.cooperative',        'en', 'Cooperative - Players work together'),
  ('sessions.setup.type.cooperative',        'fr', 'Coopératif - Les joueurs coopèrent'),
  ('sessions.setup.type.campaign',           'en', 'Campaign - Ongoing story mode'),
  ('sessions.setup.type.campaign',           'fr', 'Campagne - Mode histoire'),
  ('sessions.setup.type.hybrid',             'en', 'Hybrid - Mix of team and individual goals'),
  ('sessions.setup.type.hybrid',             'fr', 'Hybride - Mélange d''objectifs équipe et individuels'),
  ('sessions.players.title',                 'en', 'Select Players'),
  ('sessions.players.title',                 'fr', 'Sélectionner les joueurs'),
  ('sessions.cooperative.title',             'en', 'Cooperative Objectives'),
  ('sessions.cooperative.title',             'fr', 'Objectifs coopératifs'),
  ('sessions.cooperative.difficulty.label',  'en', 'Difficulty Level'),
  ('sessions.cooperative.difficulty.label',  'fr', 'Niveau de difficulté'),
  ('sessions.cooperative.team_success',      'en', 'Team Victory'),
  ('sessions.cooperative.team_success',      'fr', 'Victoire d''équipe'),
  ('sessions.cooperative.team_score.label',  'en', 'Team Score'),
  ('sessions.cooperative.team_score.label',  'fr', 'Score d''équipe'),
  ('sessions.cooperative.objectives.label',  'en', 'Shared Objectives'),
  ('sessions.cooperative.objectives.label',  'fr', 'Objectifs partagés'),
  ('sessions.cooperative.objectives.add_common', 'en', 'Add Common'),
  ('sessions.cooperative.objectives.add_common', 'fr', 'Ajouter communs'),
  ('sessions.cooperative.objectives.add_custom', 'en', 'Add Custom'),
  ('sessions.cooperative.objectives.add_custom', 'fr', 'Ajouter personnalisé'),
  ('sessions.cooperative.objectives.empty',      'en', 'No objectives set yet'),
  ('sessions.cooperative.objectives.empty',      'fr', 'Aucun objectif défini'),
  ('sessions.cooperative.objectives.completed',  'en', 'Completed'),
  ('sessions.cooperative.objectives.completed',  'fr', 'Accompli'),
  ('sessions.competitive.title',             'en', 'Competitive Scoring'),
  ('sessions.competitive.title',             'fr', 'Scores compétitifs'),
  ('sessions.competitive.winner_missing',    'en', 'A winner must be designated'),
  ('sessions.competitive.winner_missing',    'fr', 'Un vainqueur doit être désigné'),
  ('sessions.competitive.score_invalid',     'en', 'The winner''s score must be greater than 0'),
  ('sessions.competitive.score_invalid',     'fr', 'Le score du vainqueur doit être supérieur à 0'),
  ('sessions.competitive.winner',            'en', 'Winner'),
  ('sessions.competitive.winner',            'fr', 'Vainqueur'),
  ('sessions.hybrid.team.title',             'en', 'Team Objectives'),
  ('sessions.hybrid.team.title',             'fr', 'Objectifs d''équipe'),
  ('sessions.hybrid.team.completed',         'en', 'Team Objectives Completed'),
  ('sessions.hybrid.team.completed',         'fr', 'Objectifs d''équipe accomplis'),
  ('sessions.hybrid.team.score',             'en', 'Team Score'),
  ('sessions.hybrid.team.score',             'fr', 'Score d''équipe'),
  ('sessions.hybrid.individual.title',       'en', 'Individual Scores'),
  ('sessions.hybrid.individual.title',       'fr', 'Scores individuels'),
  ('sessions.details.title',                 'en', 'Session Details'),
  ('sessions.details.title',                 'fr', 'Détails de la session'),
  ('sessions.details.duration.label',        'en', 'Duration (minutes)'),
  ('sessions.details.duration.label',        'fr', 'Durée (minutes)'),
  ('sessions.details.duration.required',     'en', 'Required'),
  ('sessions.details.duration.required',     'fr', 'Obligatoire'),
  ('sessions.details.notes.label',           'en', 'Notes'),
  ('sessions.details.notes.label',           'fr', 'Notes'),
  ('sessions.details.notes.placeholder',     'en', 'Game notes, highlights, or observations...'),
  ('sessions.details.notes.placeholder',     'fr', 'Notes, moments forts ou observations...'),
  ('sessions.submit',                        'en', 'Create Session'),
  ('sessions.submit',                        'fr', 'Créer la session'),
  ('sessions.submit.loading',                'en', 'Creating...'),
  ('sessions.submit.loading',                'fr', 'Création...'),

  -- stats page
  ('stats.page.title',    'en', 'Statistics'),
  ('stats.page.title',    'fr', 'Statistiques'),
  ('stats.tab.players',   'en', 'Player Stats'),
  ('stats.tab.players',   'fr', 'Stats joueurs'),
  ('stats.tab.games',     'en', 'Game Stats'),
  ('stats.tab.games',     'fr', 'Stats jeux'),

  -- stats game
  ('stats.game.no_data',            'en', 'No game data available'),
  ('stats.game.no_data',            'fr', 'Aucune donnée disponible'),
  ('stats.game.all_title',          'en', 'All Games Statistics'),
  ('stats.game.all_title',          'fr', 'Statistiques tous jeux'),
  ('stats.game.stat.sessions',      'en', 'Sessions'),
  ('stats.game.stat.sessions',      'fr', 'Sessions'),
  ('stats.game.stat.avg_players',   'en', 'Avg Players'),
  ('stats.game.stat.avg_players',   'fr', 'Joueurs moy.'),
  ('stats.game.stat.avg_duration',  'en', 'Avg Duration'),
  ('stats.game.stat.avg_duration',  'fr', 'Durée moy.'),
  ('stats.game.stat.avg_score',     'en', 'Avg Score'),
  ('stats.game.stat.avg_score',     'fr', 'Score moy.'),
  ('stats.game.back_to_all',        'en', '← Back to All Games Statistics'),
  ('stats.game.back_to_all',        'fr', '← Retour aux statistiques globales'),
  ('stats.game.select.title',       'en', 'Select a Game for Detailed Stats'),
  ('stats.game.select.title',       'fr', 'Choisir un jeu pour les stats détaillées'),
  ('stats.game.popularity.title',   'en', 'Game Popularity'),
  ('stats.game.popularity.title',   'fr', 'Popularité des jeux'),
  ('stats.game.sessions_label',     'en', 'sessions'),
  ('stats.game.sessions_label',     'fr', 'sessions'),
  ('stats.game.score_trend.title',  'en', 'Score Trend'),
  ('stats.game.score_trend.title',  'fr', 'Évolution des scores'),
  ('stats.game.score_trend.subtitle','en', 'Last 10 Sessions'),
  ('stats.game.score_trend.subtitle','fr', '10 dernières sessions'),
  ('stats.game.session_types.title','en', 'Session Types'),
  ('stats.game.session_types.title','fr', 'Types de sessions'),
  ('stats.game.player_dist.title',  'en', 'Player Count Distribution'),
  ('stats.game.player_dist.title',  'fr', 'Distribution nb joueurs'),
  ('stats.game.player_dist.label',  'en', 'players'),
  ('stats.game.player_dist.label',  'fr', 'joueurs'),
  ('stats.game.top_winners.title',  'en', 'Top Winners'),
  ('stats.game.top_winners.title',  'fr', 'Meilleurs joueurs'),
  ('stats.game.top_winners.wins',   'en', 'wins'),
  ('stats.game.top_winners.wins',   'fr', 'victoires'),
  ('stats.game.recent.title',       'en', 'Recent Sessions'),
  ('stats.game.recent.title',       'fr', 'Sessions récentes'),
  ('stats.game.recent.winner',      'en', 'Winner:'),
  ('stats.game.recent.winner',      'fr', 'Vainqueur :'),
  ('stats.game.recent.avg_score',   'en', 'avg score'),
  ('stats.game.recent.avg_score',   'fr', 'score moy.'),

  -- stats player
  ('stats.player.profile',            'en', 'Player Profile'),
  ('stats.player.profile',            'fr', 'Profil joueur'),
  ('stats.player.stat.wins',          'en', 'Wins'),
  ('stats.player.stat.wins',          'fr', 'Victoires'),
  ('stats.player.stat.games_played',  'en', 'Games Played'),
  ('stats.player.stat.games_played',  'fr', 'Parties jouées'),
  ('stats.player.stat.total_score',   'en', 'Total Score'),
  ('stats.player.stat.total_score',   'fr', 'Score total'),
  ('stats.player.stat.avg_score',     'en', 'Avg Score'),
  ('stats.player.stat.avg_score',     'fr', 'Score moyen'),
  ('stats.player.stat.total_players', 'en', 'Total Players'),
  ('stats.player.stat.total_players', 'fr', 'Total joueurs'),
  ('stats.player.favorite_game',      'en', 'Favorite Game'),
  ('stats.player.favorite_game',      'fr', 'Jeu favori'),
  ('stats.player.top_players',        'en', 'Top Players'),
  ('stats.player.top_players',        'fr', 'Meilleurs joueurs'),
  ('stats.player.recent.empty',       'en', 'No recent games found'),
  ('stats.player.recent.empty',       'fr', 'Aucune partie récente'),
  ('stats.player.recent.winner',      'en', 'Winner'),
  ('stats.player.recent.winner',      'fr', 'Vainqueur'),
  ('stats.player.activity.title',     'en', 'Recent Activity'),
  ('stats.player.activity.title',     'fr', 'Activité récente'),
  ('stats.player.performance.coming_soon','en', 'Detailed charts coming soon...'),
  ('stats.player.performance.coming_soon','fr', 'Graphiques détaillés à venir...'),

  -- settings
  ('settings.page.title',            'en', 'Settings'),
  ('settings.page.title',            'fr', 'Paramètres'),
  ('settings.section.preferences',   'en', 'Preferences'),
  ('settings.section.preferences',   'fr', 'Préférences'),
  ('settings.notifications.label',   'en', 'Notifications'),
  ('settings.notifications.label',   'fr', 'Notifications'),
  ('settings.notifications.desc',    'en', 'Get notified about game updates'),
  ('settings.notifications.desc',    'fr', 'Recevoir les mises à jour'),
  ('settings.dark_mode.label',       'en', 'Dark Mode'),
  ('settings.dark_mode.label',       'fr', 'Mode sombre'),
  ('settings.dark_mode.desc',        'en', 'Use dark theme'),
  ('settings.dark_mode.desc',        'fr', 'Utiliser le thème sombre'),
  ('settings.language.label',        'en', 'Language'),
  ('settings.language.label',        'fr', 'Langue'),
  ('settings.language.desc',         'en', 'Choose your language'),
  ('settings.language.desc',         'fr', 'Choisir votre langue'),
  ('settings.language.offline',      'en', 'Unavailable offline'),
  ('settings.language.offline',      'fr', 'Indisponible hors ligne'),
  ('settings.language.retry',        'en', 'Retry'),
  ('settings.language.retry',        'fr', 'Réessayer'),
  ('settings.auto_save.label',       'en', 'Auto Save'),
  ('settings.auto_save.label',       'fr', 'Sauvegarde auto'),
  ('settings.auto_save.desc',        'en', 'Automatically save changes'),
  ('settings.auto_save.desc',        'fr', 'Enregistrer automatiquement'),
  ('settings.tooltips.label',        'en', 'Show Tooltips'),
  ('settings.tooltips.label',        'fr', 'Afficher les infobulles'),
  ('settings.tooltips.desc',         'en', 'Display helpful tooltips'),
  ('settings.tooltips.desc',         'fr', 'Afficher des bulles d''aide au survol'),
  ('settings.section.data',          'en', 'Data Management'),
  ('settings.section.data',          'fr', 'Gestion des données'),
  ('settings.data.bgg_imported',     'en', 'BGG Catalog imported'),
  ('settings.data.bgg_imported',     'fr', 'Catalogue BGG importé'),
  ('settings.data.export',           'en', 'Export Data'),
  ('settings.data.export',           'fr', 'Exporter les données'),
  ('settings.data.import',           'en', 'Import Data'),
  ('settings.data.import',           'fr', 'Importer les données'),
  ('settings.data.reset',            'en', 'Reset All Data'),
  ('settings.data.reset',            'fr', 'Réinitialiser toutes les données'),
  ('settings.data.bgg_catalog',      'en', 'BGG Catalog'),
  ('settings.data.bgg_catalog',      'fr', 'Catalogue BGG'),
  ('settings.data.bgg_not_imported', 'en', 'Not imported'),
  ('settings.data.bgg_not_imported', 'fr', 'Non importé'),
  ('settings.data.bgg_importing',    'en', 'Import in progress…'),
  ('settings.data.bgg_importing',    'fr', 'Import en cours…'),
  ('settings.data.bgg_import_file',  'en', 'Import boardgames_ranks.csv'),
  ('settings.data.bgg_import_file',  'fr', 'Importer boardgames_ranks.csv'),
  ('settings.data.bgg_catalog_games','en', 'games'),
  ('settings.data.bgg_catalog_games','fr', 'jeux'),
  ('settings.section.about',         'en', 'About'),
  ('settings.section.about',         'fr', 'À propos'),
  ('settings.about.version',         'en', 'Board Game Dashboard v1.0.0'),
  ('settings.about.version',         'fr', 'Board Game Dashboard v1.0.0'),
  ('settings.about.desc',            'en', 'A modern dashboard for tracking your board game sessions and player statistics.'),
  ('settings.about.desc',            'fr', 'Un tableau de bord moderne pour suivre vos sessions et statistiques.'),
  ('settings.section.session',       'en', 'Session'),
  ('settings.section.session',       'fr', 'Session'),
  ('settings.logout',                'en', 'Sign out'),
  ('settings.logout',                'fr', 'Se déconnecter'),

  -- errors
  ('errors.generic',               'en', 'An error occurred'),
  ('errors.generic',               'fr', 'Une erreur est survenue'),
  ('errors.network',               'en', 'Network error. Please check your connection.'),
  ('errors.network',               'fr', 'Erreur réseau. Vérifiez votre connexion.'),
  ('errors.game.not_found',        'en', 'Game not found'),
  ('errors.game.not_found',        'fr', 'Jeu introuvable'),
  ('errors.game.duplicate',        'en', 'This game is already in your collection'),
  ('errors.game.duplicate',        'fr', 'Ce jeu est déjà dans votre collection'),
  ('errors.player.not_found',      'en', 'Player not found'),
  ('errors.player.not_found',      'fr', 'Joueur introuvable'),
  ('errors.player.duplicate_pseudo','en','This pseudo is already taken'),
  ('errors.player.duplicate_pseudo','fr','Ce pseudo est déjà utilisé'),
  ('errors.session.not_found',     'en', 'Session not found'),
  ('errors.session.not_found',     'fr', 'Session introuvable'),
  ('errors.auth.unauthorized',     'en', 'Unauthorized'),
  ('errors.auth.unauthorized',     'fr', 'Non autorisé'),
  ('errors.auth.wrong_password',   'en', 'Incorrect password'),
  ('errors.auth.wrong_password',   'fr', 'Mot de passe incorrect'),
  ('errors.server',                'en', 'Server error. Please try again later.'),
  ('errors.server',                'fr', 'Erreur serveur. Veuillez réessayer plus tard.');
