-- Character dialog and form labels
INSERT OR IGNORE INTO labels (key, locale, value) VALUES
  ('character.form.name.label', 'en', 'Character Name *'),
  ('character.form.name.label', 'fr', 'Nom du personnage *'),
  ('character.form.name.placeholder', 'en', 'Character name'),
  ('character.form.name.placeholder', 'fr', 'Nom du personnage'),
  ('character.form.key.label', 'en', 'Character Key *'),
  ('character.form.key.label', 'fr', 'Clé du personnage *'),
  ('character.form.key.placeholder', 'en', 'warrior, mage, archer...'),
  ('character.form.key.placeholder', 'fr', 'warrior, mage, archer...'),
  ('character.form.key.hint', 'en', 'Unique identifier (will be auto-formatted)'),
  ('character.form.key.hint', 'fr', 'Identifiant unique (sera automatiquement formaté)'),
  ('character.form.avatar.label', 'en', 'Avatar (URL)'),
  ('character.form.avatar.label', 'fr', 'Avatar (URL)'),
  ('character.form.description.label', 'en', 'Description'),
  ('character.form.description.label', 'fr', 'Description'),
  ('character.form.description.placeholder', 'en', 'Character description...'),
  ('character.form.description.placeholder', 'fr', 'Description du personnage...'),
  ('character.form.abilities.label', 'en', 'Abilities'),
  ('character.form.abilities.label', 'fr', 'Capacités'),
  ('character.form.abilities.placeholder', 'en', 'Heavy attack, Shield, Intimidation...'),
  ('character.form.abilities.placeholder', 'fr', 'Attaque lourde, Bouclier, Intimidation...'),
  ('character.form.abilities.hint', 'en', 'Separate abilities with commas'),
  ('character.form.abilities.hint', 'fr', 'Séparez les capacités par des virgules'),
  ('character.dialog.add.title', 'en', 'Add Character'),
  ('character.dialog.add.title', 'fr', 'Ajouter un personnage'),
  ('character.dialog.add.description', 'en', 'Add a new character/role for this game.'),
  ('character.dialog.add.description', 'fr', 'Ajoutez un nouveau personnage/rôle pour ce jeu.'),
  ('character.dialog.edit.title', 'en', 'Edit Character'),
  ('character.dialog.edit.title', 'fr', 'Modifier le personnage'),
  ('character.dialog.edit.description', 'en', 'Update the information for this character/role.'),
  ('character.dialog.edit.description', 'fr', 'Modifiez les informations de ce personnage/rôle.'),
  ('character.dialog.delete.title', 'en', 'Delete Character'),
  ('character.dialog.delete.title', 'fr', 'Supprimer le personnage'),
  ('character.dialog.delete.description', 'en', 'Are you sure you want to delete this character? This action cannot be undone.'),
  ('character.dialog.delete.description', 'fr', 'Êtes-vous sûr de vouloir supprimer ce personnage ? Cette action est irréversible.');
