-- Expansion dialog and form labels
INSERT OR IGNORE INTO labels (key, locale, value) VALUES
  ('expansion.form.name.label', 'en', 'Expansion Name *'),
  ('expansion.form.name.label', 'fr', 'Nom de l''extension *'),
  ('expansion.form.name.placeholder', 'en', 'Expansion name'),
  ('expansion.form.name.placeholder', 'fr', 'Nom de l''extension'),
  ('expansion.form.year.label', 'en', 'Year Published'),
  ('expansion.form.year.label', 'fr', 'Année de publication'),
  ('expansion.form.bgg_id.label', 'en', 'BGG ID'),
  ('expansion.form.bgg_id.label', 'fr', 'ID BGG'),
  ('expansion.form.bgg_id.placeholder', 'en', 'BoardGameGeek ID'),
  ('expansion.form.bgg_id.placeholder', 'fr', 'ID BoardGameGeek'),
  ('expansion.form.description.placeholder', 'en', 'Expansion description...'),
  ('expansion.form.description.placeholder', 'fr', 'Description de l''extension...'),
  ('expansion.dialog.add.title', 'en', 'Add Expansion'),
  ('expansion.dialog.add.title', 'fr', 'Ajouter une extension'),
  ('expansion.dialog.add.description', 'en', 'Add a new expansion for this game.'),
  ('expansion.dialog.add.description', 'fr', 'Ajoutez une nouvelle extension pour ce jeu.'),
  ('expansion.dialog.edit.title', 'en', 'Edit Expansion'),
  ('expansion.dialog.edit.title', 'fr', 'Modifier l''extension'),
  ('expansion.dialog.edit.description', 'en', 'Update the information for this expansion.'),
  ('expansion.dialog.edit.description', 'fr', 'Modifiez les informations de cette extension.'),
  ('expansion.dialog.delete.title', 'en', 'Delete Expansion'),
  ('expansion.dialog.delete.title', 'fr', 'Supprimer l''extension'),
  ('expansion.dialog.delete.description', 'en', 'Are you sure you want to delete this expansion? This action cannot be undone.'),
  ('expansion.dialog.delete.description', 'fr', 'Êtes-vous sûr de vouloir supprimer cette extension ? Cette action est irréversible.');
