-- Characters and Expansions view labels
INSERT OR IGNORE INTO labels (key, locale, value) VALUES
  ('character.view.title', 'en', 'Characters'),
  ('character.view.title', 'fr', 'Personnages'),
  ('character.view.back_to_detail', 'en', 'Back to game details'),
  ('character.view.back_to_detail', 'fr', 'Retour aux détails du jeu'),
  ('character.view.back_to_games', 'en', 'Back to games list'),
  ('character.view.back_to_games', 'fr', 'Retour à la liste des jeux'),
  ('character.view.empty', 'en', 'No characters added for this game.'),
  ('character.view.empty', 'fr', 'Aucun personnage ajouté pour ce jeu.'),
  ('character.view.add_first', 'en', 'Add First Character'),
  ('character.view.add_first', 'fr', 'Ajouter le premier personnage'),
  ('character.tooltip.edit', 'en', 'Edit Character'),
  ('character.tooltip.edit', 'fr', 'Modifier le personnage'),
  ('character.tooltip.delete', 'en', 'Delete Character'),
  ('character.tooltip.delete', 'fr', 'Supprimer le personnage'),
  ('expansion.view.title', 'en', 'Expansions'),
  ('expansion.view.title', 'fr', 'Extensions'),
  ('expansion.view.back_to_detail', 'en', 'Back to Game Details'),
  ('expansion.view.back_to_detail', 'fr', 'Retour aux détails du jeu'),
  ('expansion.view.back_to_games', 'en', 'Back to Games List'),
  ('expansion.view.back_to_games', 'fr', 'Retour à la liste des jeux'),
  ('expansion.view.add_new', 'en', 'Add Expansion'),
  ('expansion.view.add_new', 'fr', 'Ajouter une extension'),
  ('expansion.view.empty', 'en', 'No expansions added for this game.'),
  ('expansion.view.empty', 'fr', 'Aucune extension ajoutée pour ce jeu.'),
  ('expansion.view.add_first', 'en', 'Add First Expansion'),
  ('expansion.view.add_first', 'fr', 'Ajouter la première extension'),
  ('expansion.tooltip.edit', 'en', 'Edit Expansion'),
  ('expansion.tooltip.edit', 'fr', 'Modifier l''extension'),
  ('expansion.tooltip.delete', 'en', 'Delete Expansion'),
  ('expansion.tooltip.delete', 'fr', 'Supprimer l''extension'),
  ('expansion.tooltip.add', 'en', 'Add New Expansion'),
  ('expansion.tooltip.add', 'fr', 'Ajouter une nouvelle extension');
