-- Game form and dialog labels
INSERT OR IGNORE INTO labels (key, locale, value) VALUES
  ('games.add_dialog.description', 'en', 'Add a new game to your collection by filling out the details below.'),
  ('games.add_dialog.description', 'fr', 'Ajoutez un nouveau jeu à votre collection en remplissant les détails ci-dessous.'),
  ('games.edit_dialog.description', 'en', 'Update game information and details.'),
  ('games.edit_dialog.description', 'fr', 'Modifiez les informations et détails du jeu.'),
  ('games.form.bgg_search', 'en', 'Search BoardGameGeek'),
  ('games.form.bgg_search', 'fr', 'Rechercher sur BoardGameGeek'),
  ('games.form.image.label', 'en', 'Image URL'),
  ('games.form.image.label', 'fr', 'URL de l''image'),
  ('games.form.thumbnail.label', 'en', 'Thumbnail URL'),
  ('games.form.thumbnail.label', 'fr', 'URL de la vignette'),
  ('games.form.min_players.label', 'en', 'Min Players'),
  ('games.form.min_players.label', 'fr', 'Joueurs min'),
  ('games.form.max_players.label', 'en', 'Max Players'),
  ('games.form.max_players.label', 'fr', 'Joueurs max'),
  ('games.form.duration.label', 'en', 'Duration'),
  ('games.form.duration.label', 'fr', 'Durée'),
  ('games.form.age_min.label', 'en', 'Min Age'),
  ('games.form.age_min.label', 'fr', 'Âge minimum'),
  ('games.form.min_playtime.label', 'en', 'Min Playtime (min)'),
  ('games.form.min_playtime.label', 'fr', 'Durée min (min)'),
  ('games.form.playing_time.label', 'en', 'Recommended Playtime (min)'),
  ('games.form.playing_time.label', 'fr', 'Durée recommandée (min)'),
  ('games.form.max_playtime.label', 'en', 'Max Playtime (min)'),
  ('games.form.max_playtime.label', 'fr', 'Durée max (min)'),
  ('games.form.difficulty.label', 'en', 'Difficulty'),
  ('games.form.difficulty.label', 'fr', 'Difficulté'),
  ('games.form.difficulty.beginner', 'en', 'Beginner'),
  ('games.form.difficulty.beginner', 'fr', 'Débutant'),
  ('games.form.difficulty.intermediate', 'en', 'Intermediate'),
  ('games.form.difficulty.intermediate', 'fr', 'Intermédiaire'),
  ('games.form.difficulty.expert', 'en', 'Expert'),
  ('games.form.difficulty.expert', 'fr', 'Expert'),
  ('games.form.categories.label', 'en', 'Categories'),
  ('games.form.categories.label', 'fr', 'Catégories'),
  ('games.form.categories.placeholder', 'en', 'Strategy, Adventure, ...'),
  ('games.form.categories.placeholder', 'fr', 'Stratégie, Aventure, ...'),
  ('games.form.category.placeholder', 'en', 'Strategy, Party, etc.'),
  ('games.form.category.placeholder', 'fr', 'Stratégie, Ambiance, ...'),
  ('games.form.mechanics.label', 'en', 'Mechanics'),
  ('games.form.mechanics.label', 'fr', 'Mécaniques'),
  ('games.form.mechanics.placeholder', 'en', 'Hand management, Cooperative play, ...'),
  ('games.form.mechanics.placeholder', 'fr', 'Gestion de main, Jeu coopératif, ...'),
  ('games.form.designer.placeholder', 'en', 'Game designer'),
  ('games.form.designer.placeholder', 'fr', 'Auteur du jeu'),
  ('games.form.publisher.placeholder', 'en', 'Publisher name'),
  ('games.form.publisher.placeholder', 'fr', 'Nom de l''éditeur'),
  ('games.form.weight.label', 'en', 'Weight (1-5)'),
  ('games.form.weight.label', 'fr', 'Complexité (1-5)'),
  ('games.form.has_expansion_checkbox.label', 'en', 'Has expansions'),
  ('games.form.has_expansion_checkbox.label', 'fr', 'A des extensions'),
  ('games.form.is_expansion_checkbox.label', 'en', 'Is an expansion'),
  ('games.form.is_expansion_checkbox.label', 'fr', 'Est une extension'),
  ('games.form.character.add', 'en', 'Add Character'),
  ('games.form.character.add', 'fr', 'Ajouter un personnage'),
  ('games.form.character.description.placeholder', 'en', 'Character description'),
  ('games.form.character.description.placeholder', 'fr', 'Description du personnage'),
  ('games.form.character.add_ability', 'en', 'Add Ability'),
  ('games.form.character.add_ability', 'fr', 'Ajouter une capacité'),
  ('games.form.characters.roles_section', 'en', 'Characters/Roles'),
  ('games.form.characters.roles_section', 'fr', 'Personnages/Rôles'),
  ('sessions.objectives.hint', 'en', 'Add objectives to track your team''s progress'),
  ('sessions.objectives.hint', 'fr', 'Ajoutez des objectifs pour suivre la progression de l''équipe'),
  ('sessions.objectives.total_score', 'en', 'Total Objectives Score:'),
  ('sessions.objectives.total_score', 'fr', 'Score total des objectifs :');
